import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'FR' | 'EN' | 'ES' | 'DE' | 'ZH';

export const translations = {
  FR: {
    // Navbar
    nav_home: 'Accueil',
    nav_vehicles: 'Nos Véhicules',
    nav_workshop: 'Atelier & SAV',
    nav_contact: 'Contact',
    nav_book: 'Réserver',
    lang_label: 'Langue',

    // Home Hero rotating lines
    hero_line1_top: 'La voiture qu\'il vous faut,',
    hero_line1_bottom: 'là où vous en avez besoin.',
    hero_line2_top: 'La flexibilité dont vous avez besoin,',
    hero_line2_bottom: 'au prix qu\'il vous faut.',
    hero_line3_top: 'Avec ou sans chauffeur,',
    hero_line3_bottom: 'à Cotonou et dans tout le Bénin.',
    hero_scroll: 'Défiler vers le bas',

    // Home Hero
    hero_badge: 'À partir de 20 000 FCFA / jour',
    hero_welcome: 'Bienvenue chez',
    hero_subtitle: 'La voiture idéale à petit prix. Avec ou sans chauffeur, à Cotonou et dans tout le Bénin — aéroport, hôtels et toutes destinations.',
    hero_cta_whatsapp: 'Réserver sur WhatsApp',
    hero_cta_fleet: 'Voir nos véhicules',

    // Stats
    stat_vehicles: 'Véhicules disponibles',
    stat_availability: 'Disponibilité',
    stat_countries: 'Pays desservis',
    stat_price: 'FCFA / jour',

    // Services
    services_badge: 'Pourquoi nous choisir',
    services_title: 'Nos',
    services_title2: 'Services',
    services_subtitle: 'Une agence de location de proximité, pensée pour vos trajets du quotidien comme pour vos voyages.',
    service1_title: 'Avec ou sans chauffeur',
    service1_desc: 'Forfait à la journée ou longue durée, avec des chauffeurs expérimentés et un service sur mesure selon vos besoins.',
    service2_title: 'Transfert aéroport',
    service2_desc: "Votre véhicule vous attend dès la sortie de l'aéroport de Cotonou pour démarrer votre séjour sans attendre.",
    service3_title: 'Voyages privés',
    service3_desc: 'Déplacements organisés vers le Nord Bénin, le Togo et le Ghana, avec un véhicule adapté à votre trajet.',
    service4_title: 'Disponible 7j/7',
    service4_desc: "Joignable tous les jours de la semaine pour toute demande de réservation ou d'information.",

    // Fleet
    fleet_badge: 'Notre flotte',
    fleet_title: 'Nos',
    fleet_title2: 'Véhicules',
    fleet_subtitle: 'Berlines, SUV, pick-up et minibus — entretenus et disponibles à la location.',
    fleet_cta: 'Voir toute la flotte',

    // CTA
    cta_title: "Prêt à Vivre l'Expérience",
    cta_subtitle: 'Basés à Houéyiho, Cotonou — disponibles 7j/7. Réservez directement sur WhatsApp ou contactez-nous pour un devis personnalisé.',
    cta_whatsapp: 'Réserver sur WhatsApp',
    cta_contact: 'Nous contacter',

    // Contact
    // contact_badge: 'Contactez-nous',
    contact_title: 'Contactez-',
    contact_title2: 'nous',
    contact_subtitle: 'Une question ? Une réservation ? Notre équipe est disponible 7j/7 pour vous accompagner dans votre projet de location.',
    contact_form_title: 'Envoyez-nous un message',
    contact_form_subtitle: 'Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais. Vous pouvez aussi nous joindre directement sur WhatsApp.',
    contact_name: 'Nom complet',
    contact_email: 'Email',
    contact_phone: 'Téléphone',
    contact_type: 'Type de location',
    contact_subject: 'Sujet',
    contact_message: 'Message',
    contact_send: 'Envoyer le message',
    contact_sent_title: 'Message Envoyé !',
    contact_sent_subtitle: 'Merci de nous avoir contactés. Nous vous répondrons très bientôt.',
    contact_map_link: 'Houéyiho, Cotonou — Ouvrir dans Google Maps →',

    // Footer
    footer_desc: 'Agence de location de véhicules à Cotonou, disponible 7j/7. Avec ou sans chauffeur, pour tous vos trajets au Bénin et au-delà.',
    footer_nav: 'Navigation',
    footer_services: 'Nos Services',
    footer_contact: 'Contact',
    footer_rights: 'Tous droits réservés.',
    footer_privacy: 'Politique de confidentialité',
    footer_legal: 'Mentions légales',
    footer_svc1: 'Avec chauffeur',
    footer_svc2: 'Sans chauffeur',
    footer_svc3: 'Transfert aéroport',
    footer_svc4: 'Circuit touristique',
    footer_svc5: 'Voyage Nord Bénin',
    footer_svc6: 'Déplacement Togo / Ghana',

    // Contact placeholders & static
    contact_placeholder_name: 'Votre nom',
    contact_placeholder_email: 'votre@email.com',
    contact_placeholder_phone: '+229 00 00 00 00',
    contact_placeholder_type: 'Sélectionnez un type',
    contact_placeholder_subject: 'Objet de votre message',
    contact_placeholder_message: 'Décrivez votre demande (dates, destination, nombre de passagers...)',
    contact_info_address_title: 'Adresse',
    contact_info_phone_title: 'WhatsApp / Téléphone',
    contact_info_email_title: 'Email',
    contact_info_availability_title: 'Disponibilité',
    contact_info_availability1: '7 jours sur 7',
    contact_info_availability2: '24h/24 sur WhatsApp',
    contact_type1: 'Avec chauffeur',
    contact_type2: 'Sans chauffeur',
    contact_type3: 'Circuit touristique',
    contact_type4: 'Voyage privé (Nord Bénin / Togo / Ghana)',
    contact_type5: 'Transfert aéroport',
    contact_type6: 'Longue durée',

    // FAQ Contact
    faq_title: 'Questions',
    faq_title_highlight: 'Fréquentes',
    faq_q1: 'Quel est le tarif minimum pour une location ?',
    faq_a1: 'Nos tarifs démarrent à partir de 20 000 FCFA par jour. Le prix final dépend du type de véhicule, de la durée de location et des options choisies (avec ou sans chauffeur). Contactez-nous pour un devis personnalisé.',
    faq_q2: 'Proposez-vous la livraison à l\'aéroport ?',
    faq_a2: 'Oui, nous assurons le transfert depuis l\'aéroport de Cotonou. Il vous suffit de nous communiquer vos informations de vol à l\'avance et votre véhicule vous attendra dès la sortie.',
    faq_q3: 'Peut-on louer un véhicule pour voyager hors du Bénin ?',
    faq_a3: 'Absolument. Nous organisons des déplacements privés vers le Nord Bénin (Pendjari, parc du W), le Togo et le Ghana. Ces trajets se font avec un chauffeur expérimenté qui connaît les routes.',

    // Véhicules
    veh_badge: 'Notre Stock',
    veh_title: 'Nos',
    veh_title_highlight: 'Véhicules',
    veh_subtitle: 'Berlines, SUV, pick-up et minibus — toute notre flotte disponible à la location à partir de 20 000 FCFA/jour.',
    veh_search: 'Rechercher un véhicule...',
    veh_all_brands: 'Toutes marques',
    veh_fuel: 'Carburant',
    veh_found_single: 'véhicule trouvé',
    veh_found_plural: 'véhicules trouvés',
    veh_none: 'Aucun véhicule trouvé',
    veh_book: 'Réserver',

    // Workshop
    ws_badge: 'Nos Implantations',
    ws_title: 'Nos',
    ws_title_highlight: 'Ateliers & SAV',
    ws_title_rest: 'en Afrique de l\'Ouest',
    ws_subtitle: 'Nous sommes présents pour vous servir au plus près de vos besoins.',
    ws_showroom: 'Showroom',
    ws_approved: 'Atelier Agréé',
    ws_address: 'Adresse',
    ws_phone: 'Téléphone',
    ws_hours: 'Horaires',
    ws_services_label: 'Services disponibles',
    ws_maps: 'Voir sur Google Maps',
    ws_cta_title: 'Besoin d\'un',
    ws_cta_title_highlight: 'Entretien',
    ws_cta_subtitle: 'Prenez rendez-vous dès maintenant dans l\'atelier le plus proche de chez vous.',
    ws_cta_btn: 'Prendre rendez-vous',

    // Brands
    brands_badge: 'Notre Catalogue',
    brands_title: 'Nos',
    brands_title_highlight: 'Marques',
    brands_subtitle: 'Explorez notre gamme exclusive de marques automobiles prestigieuses. Cliquez sur une marque pour découvrir ses véhicules.',
    brands_vehicle_count_single: 'véhicule',
    brands_vehicle_count_plural: 'véhicules',
    brands_none: 'Aucun véhicule disponible.',
    brands_quote: 'Demander un devis',
    brands_showroom: 'Visiter le showroom',

    // Messages WhatsApp pré-remplis
    wa_default: "Bonjour, j'aimerais avoir des informations sur vos services.",
    wa_home_hero: "Bonjour LoueCars 👋, j'ai visité votre site et je souhaiterais réserver un véhicule. Pouvez-vous me conseiller ?",
    wa_home_cta: "Bonjour LoueCars 👋, je souhaiterais obtenir des informations sur la location d'un véhicule. Merci de me recontacter.",
    wa_navbar_book: "Bonjour LoueCars 👋, je souhaiterais réserver un véhicule. Pouvez-vous me proposer vos disponibilités ?",
    wa_footer_social: "Bonjour LoueCars 👋, je vous contacte depuis votre site internet. J'aimerais avoir des informations.",
    wa_footer_contact: "Bonjour LoueCars 👋, j'aimerais avoir des informations sur vos services de location.",
    wa_floating_button: "Bonjour 👋, j'ai une question concernant vos services. Pouvez-vous m'aider ?",
    wa_vehicle_book: "Bonjour LoueCars 🚗, je souhaiterais réserver le véhicule suivant : {vehicle} au prix de {price} FCFA. Quelles sont les disponibilités ?",
    wa_brand_quote: "Bonjour LoueCars 🚙, je souhaiterais un devis pour un véhicule de la marque {brand}{type}. Pouvez-vous me proposer les modèles disponibles ?",
    wa_contact_form: "Bonjour LoueCars 👋, je vous contacte depuis le formulaire de votre site.\n\n👤 Nom : {name}\n📧 Email : {email}\n📞 Téléphone : {phone}\n🏷️ Sujet : {subject}\n🚗 Marque : {brand}\n\n📝 Message :\n{message}",

    // Shared
    aria_whatsapp_contact: 'Contacter sur WhatsApp',
    footer_address: 'Houéyiho, Cotonou, Bénin',
    currency_fcfa: 'FCFA',
    vehicle_type_suv: 'SUV',
    vehicle_type_pickup: 'Pick-up',
    vehicle_type_4x4: '4×4 / 4×2',
    vehicle_type_suv_4x4: 'SUV 4×4',
    vehicle_type_7seats: '7 places',
    vehicle_type_15seats: '15 places',
    stat_7j7: '7j/7',
    home_alt_hero: 'LoueCars - Location de véhicules au Bénin',
    home_alt_fleet: 'LoueCars fleet',

    // Contact cities
    contact_city_houeyiho: 'Houéyiho',
    contact_city_cotonou: 'Cotonou, Bénin',

    // Workshop data
    ws_address_cotonou: 'Boulevard de la Marina, Quartier Cadjèhoun, Cotonou',
    ws_hours_cotonou: 'Lun-Sam: 8h00 - 18h00',
    ws_address_parakou: 'Route de Malanville, Quartier Banikanni, Parakou',
    ws_hours_parakou: 'Lun-Sam: 8h00 - 17h30',
    ws_address_lome: 'Avenue de la Libération, Quartier Bè, Lomé',
    ws_hours_lome: 'Lun-Sam: 8h00 - 18h00',
    ws_address_ouaga: 'Avenue Kwame Nkrumah, Zone Industrielle, Ouagadougou',
    ws_hours_ouaga: 'Lun-Sam: 7h30 - 17h30',
    ws_svc_entretien_generale: 'Entretien général',
    ws_svc_diagnostic_electro: 'Diagnostic électronique',
    ws_svc_carrosserie: 'Carrosserie',
    ws_svc_climatisation: 'Climatisation',
    ws_svc_entretien_vehicules: 'Entretien véhicules',
    ws_svc_vidange: 'Vidange',
    ws_svc_freinage: 'Freinage',
    ws_svc_pneus: 'Pneus',
    ws_svc_mecanique_generale: 'Mécanique générale',
    ws_svc_electricite_auto: 'Électricité auto',
    ws_svc_diagnostic: 'Diagnostic',
    ws_svc_sav_complet: 'SAV complet',
    ws_svc_service_rapide: 'Service rapide',
    ws_svc_pieces_detachees: 'Pièces détachées',
    ws_svc_peinture: 'Peinture',
    ws_service1_title: 'Entretien Préventif',
    ws_service1_desc: 'Vidange, filtres, courroies, freins - tout pour maintenir votre véhicule en parfait état.',
    ws_service2_title: 'Garantie Constructeur',
    ws_service2_desc: 'Interventions effectuées selon les normes constructeur pour préserver votre garantie.',
    ws_service3_title: 'Pièces Authentiques',
    ws_service3_desc: 'Utilisation exclusive de pièces d\'origine pour une qualité optimale.',

    // Admin - Common
    admin_btn_add: 'Ajouter',
    admin_btn_edit: 'Modifier',
    admin_btn_delete: 'Supprimer',
    admin_btn_cancel: 'Annuler',
    admin_btn_login: 'Se connecter',
    admin_btn_logout: 'Déconnexion',
    admin_btn_upload_image: 'Uploader une image',
    admin_btn_upload_photo: 'Uploader une photo',
    admin_btn_reply_email: 'Répondre par email',
    admin_label_name: 'Nom *',
    admin_label_email: 'Email',
    admin_label_phone: 'Téléphone',
    admin_label_description: 'Description',
    admin_label_message: 'Message',
    admin_or: 'ou',
    admin_confirm_irreversible: 'Cette action est irréversible.',
    admin_warn_place_file_in: '⚠️ Place le fichier dans',
    admin_placeholder_search: 'Rechercher...',
    admin_all_brands: 'Toutes les marques',

    // Admin - Marques
    admin_marques_title: 'Marques',
    admin_marques_count: '{count} marque{s}',
    admin_marques_empty: 'Aucune marque. Ajoutez-en une !',
    admin_modal_edit_marque: 'Modifier la marque',
    admin_modal_new_marque: 'Nouvelle marque',
    admin_label_marque_logo: 'Logo de la marque',
    admin_placeholder_logo_url: 'URL ou chemin ex: /marques/kia.png',
    admin_placeholder_ex_kia: 'Ex: KIA',
    admin_label_type: 'Type *',
    admin_placeholder_desc_short: 'Description courte...',
    admin_confirm_delete_marque: 'Supprimer la marque ?',
    admin_confirm_delete_marque_desc: 'Les véhicules associés seront aussi supprimés.',

    // Admin - Vehicules
    admin_vehicules_title: 'Véhicules',
    admin_vehicules_count: '{count} véhicule{s}',
    admin_th_vehicle: 'Véhicule',
    admin_th_brand: 'Marque',
    admin_th_price: 'Prix',
    admin_th_fuel: 'Carburant',
    admin_th_status: 'Statut',
    admin_th_actions: 'Actions',
    admin_from_price: 'À partir de',
    admin_vehicules_empty: 'Aucun véhicule trouvé',
    admin_modal_edit_vehicle: 'Modifier le véhicule',
    admin_modal_new_vehicle: 'Nouveau véhicule',
    admin_label_vehicle_photo: 'Photo du véhicule',
    admin_alt_vehicle: 'véhicule',
    admin_placeholder_image_url: 'URL ou chemin ex: /vehicules/kia.jpg',
    admin_label_brand: 'Marque *',
    admin_label_vehicle_name: 'Nom du véhicule *',
    admin_placeholder_ex_vehicle: 'Ex: KIA Sportage',
    admin_label_price: 'Prix (FCFA) *',
    admin_placeholder_ex_price: 'Ex: 18 500 000',
    admin_label_year: 'Année *',
    admin_label_fuel: 'Carburant',
    admin_label_transmission: 'Transmission',
    admin_label_color: 'Couleur',
    admin_placeholder_ex_color: 'Ex: Blanc',
    admin_label_status: 'Statut',
    admin_placeholder_desc_vehicle: 'Description du véhicule...',
    admin_confirm_delete_vehicle: 'Supprimer ce véhicule ?',

    // Admin - Messages
    admin_messages_title: 'Messages',
    admin_messages_count: '{count} message{s} reçu{s}',
    admin_messages_empty: 'Aucun message reçu',
    admin_messages_empty_desc: 'Les messages du formulaire de contact apparaîtront ici.',
    admin_label_brand_interest: 'Marque d\'intérêt',
    admin_label_received_on: 'Reçu le',
    admin_confirm_delete_message: 'Supprimer ce message ?',

    // Admin - Dashboard
    admin_stat_marques: 'Marques',
    admin_stat_vehicules: 'Véhicules',
    admin_stat_available: 'Disponibles',
    admin_stat_messages: 'Messages',
    admin_dashboard_title: 'Dashboard',
    admin_dashboard_subtitle: 'Vue d\'ensemble de votre catalogue',
    admin_unread: 'non lu{s}',
    admin_recent_vehicles: 'Véhicules récents',
    admin_see_all: 'Voir tout',
    admin_no_vehicles: 'Aucun véhicule',
    admin_recent_messages: 'Messages récents',
    admin_no_messages: 'Aucun message',

    // Admin - Layout
    admin_nav_dashboard: 'Dashboard',
    admin_nav_marques: 'Marques',
    admin_nav_vehicules: 'Véhicules',
    admin_nav_messages: 'Messages',
    admin_subtitle: 'Administration',
    admin_user_label: 'Admin',

    // Admin - Login
    admin_login_error: 'Identifiants incorrects. Réessayez.',
    admin_login_title: 'Connexion',
    admin_placeholder_username: 'admin',
    admin_hint_credentials: 'admin / louecars2024',

    // Politique de confidentialité
    privacy_badge: 'Confidentialité',
    privacy_title: 'Politique de',
    privacy_title2: 'confidentialité',
    privacy_subtitle: 'Nous attachons une grande importance à la protection de vos données personnelles. Découvrez comment nous les collectons, les utilisons et les protégeons.',
    privacy_intro_title: 'Introduction',
    privacy_intro_text: "La présente politique de confidentialité explique comment LoueCars, agence de location de véhicules à Cotonou (Bénin), collecte, utilise et protège vos données personnelles lorsque vous utilisez notre site internet ou nos services.",
    privacy_data_title: 'Données que nous collectons',
    privacy_data_1: "Données d'identification : nom, prénom, adresse email et numéro de téléphone que vous fournissez via notre formulaire de contact.",
    privacy_data_2: "Données de réservation : type de véhicule, dates, destination et nombre de passagers lorsque vous nous contactez sur WhatsApp ou par email.",
    privacy_data_3: 'Données de navigation : pages visitées, durée de consultation et adresse IP, collectées via des cookies.',
    privacy_data_4: 'Données de communication : contenu des messages échangés avec notre équipe.',
    privacy_data_5: "Nous ne collectons jamais de données sensibles (origine ethnique, opinions politiques, données de santé, etc.).",
    privacy_use_title: 'Utilisation de vos données',
    privacy_use_1: 'Répondre à vos demandes de renseignements et de réservation.',
    privacy_use_2: 'Établir un devis personnalisé et préparer votre location.',
    privacy_use_3: 'Assurer le suivi de votre réservation et vous accompagner avant, pendant et après votre location.',
    privacy_use_4: 'Améliorer nos services et la qualité de notre site internet.',
    privacy_base_title: 'Base légale',
    privacy_base_text: "Vos données sont traitées sur la base de votre consentement (formulaire de contact, cookies) et de l'exécution du contrat de location que vous sollicitez. Elles ne sont en aucun cas utilisées à des fins commerciales sans votre accord.",
    privacy_retention_title: 'Conservation des données',
    privacy_retention_text: 'Vos données sont conservées uniquement pendant la durée nécessaire aux finalités décrites ci-dessus : 3 ans maximum après votre dernier contact pour les données de prospection, et 10 ans pour les documents relatifs à la location, conformément aux obligations légales et fiscales en vigueur au Bénin.',
    privacy_share_title: 'Partage des données',
    privacy_share_text: 'Vos données ne sont ni vendues, ni louées, ni cédées à des tiers. Elles sont uniquement partagées avec les prestataires strictement nécessaires à nos services (hébergeur du site, fournisseur de messagerie), et uniquement dans la mesure requise.',
    privacy_cookies_title: 'Cookies',
    privacy_cookies_text: "Notre site utilise des cookies techniques indispensables à son fonctionnement et des cookies de mesure d'audience anonymisés. Vous pouvez configurer votre navigateur pour refuser les cookies ; cela peut toutefois limiter certaines fonctionnalités du site.",
    privacy_rights_title: 'Vos droits',
    privacy_rights_1: 'Accéder à vos données personnelles.',
    privacy_rights_2: 'Demander la rectification de données inexactes ou incomplètes.',
    privacy_rights_3: 'Demander la suppression de vos données dans les conditions prévues par la loi.',
    privacy_rights_4: 'Retirer votre consentement à tout moment pour les traitements fondés sur celui-ci.',
    privacy_security_title: 'Sécurité',
    privacy_security_text: 'Nous mettons en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos données contre tout accès non autorisé, perte, altération ou divulgation.',
    privacy_contact_title: 'Nous contacter',
    privacy_contact_text: "Pour toute question concernant cette politique ou l'exercice de vos droits, contactez-nous par email à eddiecelle@gmail.com, par téléphone au +229 97 23 84 83, ou via notre page de contact.",
    privacy_updated: 'Dernière mise à jour : août 2026',

    // Mentions légales
    legal_badge: 'Informations légales',
    legal_title: 'Mentions',
    legal_title2: 'légales',
    legal_subtitle: "Informations légales relatives au site internet de l'agence LoueCars, société de location de véhicules au Bénin.",
    legal_publisher_title: 'Éditeur du site',
    legal_publisher_text: 'LoueCars — Agence de location de véhicules. Adresse : Houéyiho, Cotonou, Bénin. Email : eddiecelle@gmail.com. Téléphone : +229 97 23 84 83.',
    legal_director_title: 'Directeur de la publication',
    legal_director_text: "Le directeur de la publication est le représentant légal de l'agence LoueCars. Il est responsable de l'ensemble des contenus publiés sur ce site.",
    legal_host_title: 'Hébergement',
    legal_host_text: "Le site est hébergé par un prestataire technique assurant la disponibilité et la sécurité de la plateforme. Les coordonnées complètes de l'hébergeur sont disponibles sur demande.",
    legal_ip_title: 'Propriété intellectuelle',
    legal_ip_text: "L'ensemble des contenus de ce site (textes, logos, images, marques, structure, photographies) est protégé par le droit de la propriété intellectuelle. Toute reproduction, diffusion ou utilisation, en tout ou en partie, sans autorisation écrite préalable de LoueCars est strictement interdite.",
    legal_responsibility_title: 'Responsabilité',
    legal_responsibility_text: "LoueCars s'efforce d'assurer l'exactitude et la mise à jour des informations publiées sur ce site, mais ne saurait être tenu responsable des erreurs, omissions ou des dommages résultant de l'utilisation de ces informations. Les prix affichés sont donnés à titre indicatif et peuvent évoluer sans préavis.",
    legal_data_title: 'Données personnelles',
    legal_data_text: 'Les données collectées via notre formulaire de contact sont traitées conformément à notre politique de confidentialité, disponible sur ce site. Pour exercer vos droits (accès, rectification, suppression), contactez-nous.',
    legal_cookies_title: 'Cookies',
    legal_cookies_text: "Ce site utilise des cookies techniques et de mesure d'audience. Consultez notre politique de confidentialité pour plus de détails.",
    legal_law_title: 'Droit applicable',
    legal_law_text: 'Le présent site est régi par le droit béninois. En cas de litige, et à défaut de résolution amiable, les tribunaux de Cotonou (Bénin) seront seuls compétents.',
    legal_contact_title: 'Contact',
    legal_contact_text: 'Pour toute question relative aux mentions légales, contactez-nous à eddiecelle@gmail.com ou au +229 97 23 84 83.',
    legal_updated: 'Dernière mise à jour : août 2026',
  },

  EN: {
    nav_home: 'Home',
    nav_vehicles: 'Our Vehicles',
    nav_workshop: 'Workshop & SAV',
    nav_contact: 'Contact',
    nav_book: 'Book Now',
    lang_label: 'Language',

    hero_line1_top: 'The car you need,',
    hero_line1_bottom: 'where you need it.',
    hero_line2_top: 'The flexibility you need,',
    hero_line2_bottom: 'at the price you want.',
    hero_line3_top: 'With or without driver,',
    hero_line3_bottom: 'in Cotonou and all of Benin.',
    hero_scroll: 'Scroll down',

    hero_badge: 'From 20,000 FCFA / day',
    hero_welcome: 'Welcome to',
    hero_subtitle: 'The ideal car at a great price. With or without driver, in Cotonou and all of Benin — airport, hotels and all destinations.',
    hero_cta_whatsapp: 'Book on WhatsApp',
    hero_cta_fleet: 'View our vehicles',

    stat_vehicles: 'Available vehicles',
    stat_availability: 'Availability',
    stat_countries: 'Countries served',
    stat_price: 'FCFA / day',

    services_badge: 'Why choose us',
    services_title: 'Our',
    services_title2: 'Services',
    services_subtitle: 'A local car rental agency, designed for your daily commutes and longer journeys.',
    service1_title: 'With or without driver',
    service1_desc: 'Daily or long-term packages, with experienced drivers and a tailored service to meet your needs.',
    service2_title: 'Airport transfer',
    service2_desc: 'Your vehicle awaits you right at the exit of Cotonou airport so you can start your stay without delay.',
    service3_title: 'Private trips',
    service3_desc: 'Organized travel to Northern Benin, Togo and Ghana, with a vehicle suited to your journey.',
    service4_title: 'Available 7/7',
    service4_desc: 'Reachable every day of the week for any booking or information request.',

    fleet_badge: 'Our fleet',
    fleet_title: 'Our',
    fleet_title2: 'Vehicles',
    fleet_subtitle: 'Sedans, SUVs, pick-ups and minibuses — maintained and available for rental.',
    fleet_cta: 'View the full fleet',

    cta_title: 'Ready to Experience',
    cta_subtitle: 'Based in Houéyiho, Cotonou — available 7 days a week. Book directly on WhatsApp or contact us for a personalized quote.',
    cta_whatsapp: 'Book on WhatsApp',
    cta_contact: 'Contact us',

    // contact_badge: 'Contact us',
    contact_title: 'Contact',
    contact_title2: 'us',
    contact_subtitle: 'A question? A booking? Our team is available 7/7 to assist you with your rental project.',
    contact_form_title: 'Send us a message',
    contact_form_subtitle: 'Fill in the form below and we will get back to you as soon as possible. You can also reach us directly on WhatsApp.',
    contact_name: 'Full name',
    contact_email: 'Email',
    contact_phone: 'Phone',
    contact_type: 'Rental type',
    contact_subject: 'Subject',
    contact_message: 'Message',
    contact_send: 'Send message',
    contact_sent_title: 'Message Sent!',
    contact_sent_subtitle: 'Thank you for contacting us. We will reply very soon.',
    contact_map_link: 'Houéyiho, Cotonou — Open in Google Maps →',

    footer_desc: 'Car rental agency in Cotonou, available 7/7. With or without driver, for all your trips in Benin and beyond.',
    footer_nav: 'Navigation',
    footer_services: 'Our Services',
    footer_contact: 'Contact',
    footer_rights: 'All rights reserved.',
    footer_privacy: 'Privacy policy',
    footer_legal: 'Legal notice',
    footer_svc1: 'With driver',
    footer_svc2: 'Without driver',
    footer_svc3: 'Airport transfer',
    footer_svc4: 'Tourist circuit',
    footer_svc5: 'North Benin trip',
    footer_svc6: 'Togo / Ghana transfer',

    contact_placeholder_name: 'Your name',
    contact_placeholder_email: 'your@email.com',
    contact_placeholder_phone: '+229 00 00 00 00',
    contact_placeholder_type: 'Select a type',
    contact_placeholder_subject: 'Subject of your message',
    contact_placeholder_message: 'Describe your request (dates, destination, number of passengers...)',
    contact_info_address_title: 'Address',
    contact_info_phone_title: 'WhatsApp / Phone',
    contact_info_email_title: 'Email',
    contact_info_availability_title: 'Availability',
    contact_info_availability1: '7 days a week',
    contact_info_availability2: '24/7 on WhatsApp',
    contact_type1: 'With driver',
    contact_type2: 'Without driver',
    contact_type3: 'Tourist circuit',
    contact_type4: 'Private trip (North Benin / Togo / Ghana)',
    contact_type5: 'Airport transfer',
    contact_type6: 'Long term',

    faq_title: 'Frequently Asked',
    faq_title_highlight: 'Questions',
    faq_q1: 'What is the minimum rental rate?',
    faq_a1: 'Our rates start from 20,000 FCFA per day. The final price depends on the vehicle type, rental duration and chosen options (with or without driver). Contact us for a personalized quote.',
    faq_q2: 'Do you offer airport pickup?',
    faq_a2: 'Yes, we provide transfers from Cotonou airport. Just share your flight details in advance and your vehicle will be waiting at the exit.',
    faq_q3: 'Can I rent a vehicle to travel outside Benin?',
    faq_a3: 'Absolutely. We organize private trips to Northern Benin (Pendjari, W park), Togo and Ghana, with an experienced driver who knows the roads.',

    // Véhicules
    veh_badge: 'Our Stock',
    veh_title: 'Our',
    veh_title_highlight: 'Vehicles',
    veh_subtitle: 'Sedans, SUVs, pick-ups and minibuses — our full fleet available for rental from 20,000 FCFA/day.',
    veh_search: 'Search for a vehicle...',
    veh_all_brands: 'All brands',
    veh_fuel: 'Fuel',
    veh_found_single: 'vehicle found',
    veh_found_plural: 'vehicles found',
    veh_none: 'No vehicles found',
    veh_book: 'Book',

    // Workshop
    ws_badge: 'Our Locations',
    ws_title: 'Our',
    ws_title_highlight: 'Workshops & SAV',
    ws_title_rest: 'in West Africa',
    ws_subtitle: 'We are present to serve you as close to your needs as possible.',
    ws_showroom: 'Showroom',
    ws_approved: 'Approved Workshop',
    ws_address: 'Address',
    ws_phone: 'Phone',
    ws_hours: 'Opening hours',
    ws_services_label: 'Available services',
    ws_maps: 'View on Google Maps',
    ws_cta_title: 'Need a',
    ws_cta_title_highlight: 'Service',
    ws_cta_subtitle: 'Book an appointment now at the workshop nearest to you.',
    ws_cta_btn: 'Book an appointment',

    // Brands
    brands_badge: 'Our Catalogue',
    brands_title: 'Our',
    brands_title_highlight: 'Brands',
    brands_subtitle: 'Explore our exclusive range of prestigious automotive brands. Click on a brand to discover its vehicles.',
    brands_vehicle_count_single: 'vehicle',
    brands_vehicle_count_plural: 'vehicles',
    brands_none: 'No vehicles available.',
    brands_quote: 'Request a quote',
    brands_showroom: 'Visit the showroom',

    // Pre-filled WhatsApp messages
    wa_default: "Hello, I would like information about your services.",
    wa_home_hero: "Hello LoueCars 👋, I visited your website and would like to book a vehicle. Can you advise me?",
    wa_home_cta: "Hello LoueCars 👋, I would like to get information about renting a vehicle. Please contact me back.",
    wa_navbar_book: "Hello LoueCars 👋, I would like to book a vehicle. Can you tell me your availability?",
    wa_footer_social: "Hello LoueCars 👋, I am contacting you from your website. I would like some information.",
    wa_footer_contact: "Hello LoueCars 👋, I would like information about your rental services.",
    wa_floating_button: "Hello 👋, I have a question about your services. Can you help me?",
    wa_vehicle_book: "Hello LoueCars 🚗, I would like to book the following vehicle: {vehicle} priced at {price} FCFA. What is the availability?",
    wa_brand_quote: "Hello LoueCars 🚙, I would like a quote for a vehicle from the {brand} brand{type}. Can you suggest available models?",
    wa_contact_form: "Hello LoueCars 👋, I am contacting you from your website form.\n\n👤 Name: {name}\n📧 Email: {email}\n📞 Phone: {phone}\n🏷️ Subject: {subject}\n🚗 Brand: {brand}\n\n📝 Message:\n{message}",

    // Privacy Policy
    privacy_badge: 'Privacy',
    privacy_title: 'Privacy',
    privacy_title2: 'Policy',
    privacy_subtitle: 'We attach great importance to the protection of your personal data. Discover how we collect, use and protect it.',
    privacy_intro_title: 'Introduction',
    privacy_intro_text: 'This privacy policy explains how LoueCars, a car rental agency in Cotonou (Benin), collects, uses and protects your personal data when you use our website or our services.',
    privacy_data_title: 'Data we collect',
    privacy_data_1: 'Identification data: first name, last name, email address and phone number provided through our contact form.',
    privacy_data_2: 'Booking data: vehicle type, dates, destination and number of passengers when you contact us on WhatsApp or by email.',
    privacy_data_3: 'Browsing data: pages visited, time spent and IP address, collected through cookies.',
    privacy_data_4: 'Communication data: content of messages exchanged with our team.',
    privacy_data_5: 'We never collect sensitive data (ethnic origin, political opinions, health data, etc.).',
    privacy_use_title: 'Use of your data',
    privacy_use_1: 'Respond to your inquiries and booking requests.',
    privacy_use_2: 'Provide a personalized quote and prepare your rental.',
    privacy_use_3: 'Follow up on your booking and support you before, during and after your rental.',
    privacy_use_4: 'Improve our services and the quality of our website.',
    privacy_base_title: 'Legal basis',
    privacy_base_text: 'Your data is processed on the basis of your consent (contact form, cookies) and the performance of the rental agreement you request. It is never used for commercial purposes without your agreement.',
    privacy_retention_title: 'Data retention',
    privacy_retention_text: 'Your data is kept only for the time needed for the purposes described above: 3 years maximum after your last contact for prospecting data, and 10 years for rental-related documents, in accordance with the legal and tax obligations in force in Benin.',
    privacy_share_title: 'Data sharing',
    privacy_share_text: 'Your data is neither sold, rented nor transferred to third parties. It is only shared with providers strictly necessary to our services (website host, email provider), and only to the required extent.',
    privacy_cookies_title: 'Cookies',
    privacy_cookies_text: 'Our website uses technical cookies essential to its operation and anonymized audience-measurement cookies. You can configure your browser to refuse cookies; this may however limit some features of the site.',
    privacy_rights_title: 'Your rights',
    privacy_rights_1: 'Access your personal data.',
    privacy_rights_2: 'Request the correction of inaccurate or incomplete data.',
    privacy_rights_3: 'Request the deletion of your data under the conditions provided by law.',
    privacy_rights_4: 'Withdraw your consent at any time for processing based on it.',
    privacy_security_title: 'Security',
    privacy_security_text: 'We implement appropriate technical and organizational measures to protect your data against unauthorized access, loss, alteration or disclosure.',
    privacy_contact_title: 'Contact us',
    privacy_contact_text: 'For any question about this policy or the exercise of your rights, contact us by email at eddiecelle@gmail.com, by phone at +229 97 23 84 83, or through our contact page.',
    privacy_updated: 'Last updated: August 2026',

    // Legal Notice
    legal_badge: 'Legal information',
    legal_title: 'Legal',
    legal_title2: 'Notice',
    legal_subtitle: 'Legal information relating to the website of LoueCars, a car rental company in Benin.',
    legal_publisher_title: 'Website publisher',
    legal_publisher_text: 'LoueCars — Car rental agency. Address: Houéyiho, Cotonou, Benin. Email: eddiecelle@gmail.com. Phone: +229 97 23 84 83.',
    legal_director_title: 'Publication director',
    legal_director_text: 'The publication director is the legal representative of LoueCars. He is responsible for all content published on this website.',
    legal_host_title: 'Hosting',
    legal_host_text: 'The website is hosted by a technical provider ensuring the availability and security of the platform. The full contact details of the host are available on request.',
    legal_ip_title: 'Intellectual property',
    legal_ip_text: 'All content of this website (texts, logos, images, trademarks, structure, photographs) is protected by intellectual property law. Any reproduction, distribution or use, in whole or in part, without the prior written authorization of LoueCars is strictly prohibited.',
    legal_responsibility_title: 'Liability',
    legal_responsibility_text: 'LoueCars strives to ensure the accuracy and updating of the information published on this website, but cannot be held liable for errors, omissions or damages resulting from the use of this information. Displayed prices are indicative and may change without notice.',
    legal_data_title: 'Personal data',
    legal_data_text: 'Data collected through our contact form is processed in accordance with our privacy policy, available on this website. To exercise your rights (access, correction, deletion), contact us.',
    legal_cookies_title: 'Cookies',
    legal_cookies_text: 'This website uses technical and audience-measurement cookies. See our privacy policy for more details.',
    legal_law_title: 'Applicable law',
    legal_law_text: 'This website is governed by Beninese law. In the event of a dispute, and failing an amicable resolution, the courts of Cotonou (Benin) shall have sole jurisdiction.',
    legal_contact_title: 'Contact',
    legal_contact_text: 'For any question relating to the legal notice, contact us at eddiecelle@gmail.com or +229 97 23 84 83.',
    legal_updated: 'Last updated: August 2026',
  },

  ES: {
    nav_home: 'Inicio',
    nav_vehicles: 'Nuestros Vehículos',
    nav_workshop: 'Taller y SAV',
    nav_contact: 'Contacto',
    nav_book: 'Reservar',
    lang_label: 'Idioma',

    hero_line1_top: 'El coche que necesitas,',
    hero_line1_bottom: 'donde lo necesitas.',
    hero_line2_top: 'La flexibilidad que necesitas,',
    hero_line2_bottom: 'al precio que quieres.',
    hero_line3_top: 'Con o sin conductor,',
    hero_line3_bottom: 'en Cotonú y en todo Benín.',
    hero_scroll: 'Desplázate hacia abajo',

    hero_badge: 'Desde 20.000 FCFA / día',
    hero_welcome: 'Bienvenido a',
    hero_subtitle: 'El coche ideal a buen precio. Con o sin conductor, en Cotonú y en todo Benín — aeropuerto, hoteles y todos los destinos.',
    hero_cta_whatsapp: 'Reservar en WhatsApp',
    hero_cta_fleet: 'Ver nuestros vehículos',

    stat_vehicles: 'Vehículos disponibles',
    stat_availability: 'Disponibilidad',
    stat_countries: 'Países atendidos',
    stat_price: 'FCFA / día',

    services_badge: '¿Por qué elegirnos?',
    services_title: 'Nuestros',
    services_title2: 'Servicios',
    services_subtitle: 'Una agencia de alquiler local, pensada para sus desplazamientos diarios y sus viajes.',
    service1_title: 'Con o sin conductor',
    service1_desc: 'Paquetes por día o larga duración, con conductores experimentados y servicio personalizado.',
    service2_title: 'Traslado aeropuerto',
    service2_desc: 'Su vehículo le espera a la salida del aeropuerto de Cotonú para comenzar su estancia sin esperas.',
    service3_title: 'Viajes privados',
    service3_desc: 'Desplazamientos organizados al norte de Benín, Togo y Ghana, con vehículo adaptado a su trayecto.',
    service4_title: 'Disponible 7/7',
    service4_desc: 'Disponibles todos los días para cualquier solicitud de reserva o información.',

    fleet_badge: 'Nuestra flota',
    fleet_title: 'Nuestros',
    fleet_title2: 'Vehículos',
    fleet_subtitle: 'Berlinas, SUV, pick-ups y minibuses — mantenidos y disponibles para alquilar.',
    fleet_cta: 'Ver toda la flota',

    cta_title: '¿Listo para vivir la experiencia',
    cta_subtitle: 'Ubicados en Houéyiho, Cotonú — disponibles 7 días a la semana. Reserve directamente en WhatsApp o contáctenos para un presupuesto.',
    cta_whatsapp: 'Reservar en WhatsApp',
    cta_contact: 'Contáctenos',

    // contact_badge: 'Contáctenos',
    contact_title: 'Contáctenos',
    // contact_title2: 'Contacto',
    contact_subtitle: '¿Una pregunta? ¿Una reserva? Nuestro equipo está disponible 7/7 para ayudarle.',
    contact_form_title: 'Envíenos un mensaje',
    contact_form_subtitle: 'Rellene el formulario y le responderemos lo antes posible. También puede contactarnos directamente por WhatsApp.',
    contact_name: 'Nombre completo',
    contact_email: 'Correo electrónico',
    contact_phone: 'Teléfono',
    contact_type: 'Tipo de alquiler',
    contact_subject: 'Asunto',
    contact_message: 'Mensaje',
    contact_send: 'Enviar mensaje',
    contact_sent_title: '¡Mensaje enviado!',
    contact_sent_subtitle: 'Gracias por contactarnos. Le responderemos muy pronto.',
    contact_map_link: 'Houéyiho, Cotonú — Abrir en Google Maps →',

    footer_desc: 'Agencia de alquiler de vehículos en Cotonú, disponible 7/7. Con o sin conductor, para todos sus viajes en Benín y más allá.',
    footer_nav: 'Navegación',
    footer_services: 'Nuestros Servicios',
    footer_contact: 'Contacto',
    footer_rights: 'Todos los derechos reservados.',
    footer_privacy: 'Política de privacidad',
    footer_legal: 'Aviso legal',
    footer_svc1: 'Con conductor',
    footer_svc2: 'Sin conductor',
    footer_svc3: 'Traslado aeropuerto',
    footer_svc4: 'Circuito turístico',
    footer_svc5: 'Viaje Norte Benín',
    footer_svc6: 'Desplazamiento Togo / Ghana',

    contact_placeholder_name: 'Su nombre',
    contact_placeholder_email: 'su@email.com',
    contact_placeholder_phone: '+229 00 00 00 00',
    contact_placeholder_type: 'Seleccione un tipo',
    contact_placeholder_subject: 'Asunto de su mensaje',
    contact_placeholder_message: 'Describa su solicitud (fechas, destino, número de pasajeros...)',
    contact_info_address_title: 'Dirección',
    contact_info_phone_title: 'WhatsApp / Teléfono',
    contact_info_email_title: 'Email',
    contact_info_availability_title: 'Disponibilidad',
    contact_info_availability1: '7 días a la semana',
    contact_info_availability2: '24/7 en WhatsApp',
    contact_type1: 'Con conductor',
    contact_type2: 'Sin conductor',
    contact_type3: 'Circuito turístico',
    contact_type4: 'Viaje privado (Norte Benín / Togo / Ghana)',
    contact_type5: 'Traslado aeropuerto',
    contact_type6: 'Larga duración',

    faq_title: 'Preguntas',
    faq_title_highlight: 'Frecuentes',
    faq_q1: '¿Cuál es la tarifa mínima de alquiler?',
    faq_a1: 'Nuestras tarifas comienzan desde 20.000 FCFA por día. El precio final depende del tipo de vehículo, duración y opciones elegidas. Contáctenos para un presupuesto personalizado.',
    faq_q2: '¿Ofrecen recogida en el aeropuerto?',
    faq_a2: 'Sí, realizamos traslados desde el aeropuerto de Cotonú. Solo comparta sus datos de vuelo con antelación y su vehículo le esperará a la salida.',
    faq_q3: '¿Se puede alquilar un vehículo para viajar fuera de Benín?',
    faq_a3: 'Por supuesto. Organizamos viajes privados al norte de Benín, Togo y Ghana, con un conductor experimentado que conoce las rutas.',

    // Véhicules
    veh_badge: 'Nuestro Stock',
    veh_title: 'Nuestros',
    veh_title_highlight: 'Vehículos',
    veh_subtitle: 'Berlinas, SUV, pick-ups y minibuses — toda nuestra flota disponible para alquilar desde 20.000 FCFA/día.',
    veh_search: 'Buscar un vehículo...',
    veh_all_brands: 'Todas las marcas',
    veh_fuel: 'Combustible',
    veh_found_single: 'vehículo encontrado',
    veh_found_plural: 'vehículos encontrados',
    veh_none: 'No se encontraron vehículos',
    veh_book: 'Reservar',

    // Workshop
    ws_badge: 'Nuestras Ubicaciones',
    ws_title: 'Nuestros',
    ws_title_highlight: 'Talleres y SAV',
    ws_title_rest: 'en África Occidental',
    ws_subtitle: 'Estamos presentes para servirle lo más cerca posible de sus necesidades.',
    ws_showroom: 'Showroom',
    ws_approved: 'Taller Autorizado',
    ws_address: 'Dirección',
    ws_phone: 'Teléfono',
    ws_hours: 'Horario',
    ws_services_label: 'Servicios disponibles',
    ws_maps: 'Ver en Google Maps',
    ws_cta_title: '¿Necesita un',
    ws_cta_title_highlight: 'Mantenimiento',
    ws_cta_subtitle: 'Reserve una cita ahora en el taller más cercano a usted.',
    ws_cta_btn: 'Reservar una cita',

    // Brands
    brands_badge: 'Nuestro Catálogo',
    brands_title: 'Nuestras',
    brands_title_highlight: 'Marcas',
    brands_subtitle: 'Explore nuestra gama exclusiva de marcas de automóviles de prestigio. Haga clic en una marca para descubrir sus vehículos.',
    brands_vehicle_count_single: 'vehículo',
    brands_vehicle_count_plural: 'vehículos',
    brands_none: 'Ningún vehículo disponible.',
    brands_quote: 'Solicitar presupuesto',
    brands_showroom: 'Visitar el showroom',

    // Mensajes de WhatsApp pre-cargados
    wa_default: "Hola, me gustaría tener información sobre sus servicios.",
    wa_home_hero: "Hola LoueCars 👋, he visitado su sitio web y me gustaría reservar un vehículo. ¿Puede aconsejarme?",
    wa_home_cta: "Hola LoueCars 👋, me gustaría obtener información sobre el alquiler de un vehículo. Por favor, contácteme.",
    wa_navbar_book: "Hola LoueCars 👋, me gustaría reservar un vehículo. ¿Puede decirme su disponibilidad?",
    wa_footer_social: "Hola LoueCars 👋, le contacto desde su sitio web. Me gustaría tener algunas informaciones.",
    wa_footer_contact: "Hola LoueCars 👋, me gustaría tener información sobre sus servicios de alquiler.",
    wa_floating_button: "Hola 👋, tengo una pregunta sobre sus servicios. ¿Puede ayudarme?",
    wa_vehicle_book: "Hola LoueCars 🚗, me gustaría reservar el siguiente vehículo: {vehicle} al precio de {price} FCFA. ¿Cuál es su disponibilidad?",
    wa_brand_quote: "Hola LoueCars 🚙, me gustaría un presupuesto para un vehículo de la marca {brand}{type}. ¿Puede sugerirme modelos disponibles?",
    wa_contact_form: "Hola LoueCars 👋, le contacto desde el formulario de su sitio web.\n\n👤 Nombre: {name}\n📧 Correo: {email}\n📞 Teléfono: {phone}\n🏷️ Asunto: {subject}\n🚗 Marca: {brand}\n\n📝 Mensaje:\n{message}",

    // Política de privacidad
    privacy_badge: 'Privacidad',
    privacy_title: 'Política de',
    privacy_title2: 'privacidad',
    privacy_subtitle: 'Damos gran importancia a la protección de sus datos personales. Descubra cómo los recopilamos, utilizamos y protegemos.',
    privacy_intro_title: 'Introducción',
    privacy_intro_text: 'La presente política de privacidad explica cómo LoueCars, agencia de alquiler de vehículos en Cotonú (Benín), recopila, utiliza y protege sus datos personales cuando utiliza nuestro sitio web o nuestros servicios.',
    privacy_data_title: 'Datos que recopilamos',
    privacy_data_1: 'Datos de identificación: nombre, apellido, dirección de correo electrónico y número de teléfono que facilita a través de nuestro formulario de contacto.',
    privacy_data_2: 'Datos de reserva: tipo de vehículo, fechas, destino y número de pasajeros cuando nos contacta por WhatsApp o por correo electrónico.',
    privacy_data_3: 'Datos de navegación: páginas visitadas, tiempo de consulta y dirección IP, recopilados mediante cookies.',
    privacy_data_4: 'Datos de comunicación: contenido de los mensajes intercambiados con nuestro equipo.',
    privacy_data_5: 'Nunca recopilamos datos sensibles (origen étnico, opiniones políticas, datos de salud, etc.).',
    privacy_use_title: 'Uso de sus datos',
    privacy_use_1: 'Responder a sus solicitudes de información y reservas.',
    privacy_use_2: 'Elaborar un presupuesto personalizado y preparar su alquiler.',
    privacy_use_3: 'Realizar el seguimiento de su reserva y acompañarle antes, durante y después de su alquiler.',
    privacy_use_4: 'Mejorar nuestros servicios y la calidad de nuestro sitio web.',
    privacy_base_title: 'Base legal',
    privacy_base_text: 'Sus datos se tratan sobre la base de su consentimiento (formulario de contacto, cookies) y de la ejecución del contrato de alquiler que solicita. Nunca se utilizan con fines comerciales sin su acuerdo.',
    privacy_retention_title: 'Conservación de los datos',
    privacy_retention_text: 'Sus datos se conservan únicamente durante el tiempo necesario para los fines descritos anteriormente: 3 años como máximo después de su último contacto para datos de prospección, y 10 años para los documentos relacionados con el alquiler, de conformidad con las obligaciones legales y fiscales vigentes en Benín.',
    privacy_share_title: 'Compartición de los datos',
    privacy_share_text: 'Sus datos no se venden, alquilan ni ceden a terceros. Solo se comparten con los proveedores estrictamente necesarios para nuestros servicios (alojamiento del sitio, proveedor de correo), y únicamente en la medida requerida.',
    privacy_cookies_title: 'Cookies',
    privacy_cookies_text: 'Nuestro sitio utiliza cookies técnicas indispensables para su funcionamiento y cookies de medición de audiencia anonimizadas. Puede configurar su navegador para rechazar las cookies; esto puede limitar algunas funciones del sitio.',
    privacy_rights_title: 'Sus derechos',
    privacy_rights_1: 'Acceder a sus datos personales.',
    privacy_rights_2: 'Solicitar la rectificación de datos inexactos o incompletos.',
    privacy_rights_3: 'Solicitar la eliminación de sus datos en las condiciones previstas por la ley.',
    privacy_rights_4: 'Retirar su consentimiento en cualquier momento para los tratamientos basados en él.',
    privacy_security_title: 'Seguridad',
    privacy_security_text: 'Implementamos medidas técnicas y organizativas adecuadas para proteger sus datos contra accesos no autorizados, pérdida, alteración o divulgación.',
    privacy_contact_title: 'Contacto',
    privacy_contact_text: 'Para cualquier pregunta sobre esta política o el ejercicio de sus derechos, contáctenos por correo electrónico a eddiecelle@gmail.com, por teléfono al +229 97 23 84 83, o a través de nuestra página de contacto.',
    privacy_updated: 'Última actualización: agosto de 2026',

    // Aviso legal
    legal_badge: 'Información legal',
    legal_title: 'Aviso',
    legal_title2: 'legal',
    legal_subtitle: 'Información legal relativa al sitio web de la agencia LoueCars, empresa de alquiler de vehículos en Benín.',
    legal_publisher_title: 'Editor del sitio',
    legal_publisher_text: 'LoueCars — Agencia de alquiler de vehículos. Dirección: Houéyiho, Cotonú, Benín. Correo: eddiecelle@gmail.com. Teléfono: +229 97 23 84 83.',
    legal_director_title: 'Director de publicación',
    legal_director_text: 'El director de publicación es el representante legal de la agencia LoueCars. Es responsable de todo el contenido publicado en este sitio.',
    legal_host_title: 'Alojamiento',
    legal_host_text: 'El sitio está alojado por un proveedor técnico que garantiza la disponibilidad y la seguridad de la plataforma. Los datos completos del alojamiento están disponibles bajo petición.',
    legal_ip_title: 'Propiedad intelectual',
    legal_ip_text: 'Todo el contenido de este sitio (textos, logotipos, imágenes, marcas, estructura, fotografías) está protegido por la ley de propiedad intelectual. Cualquier reproducción, difusión o uso, total o parcial, sin autorización escrita previa de LoueCars está estrictamente prohibido.',
    legal_responsibility_title: 'Responsabilidad',
    legal_responsibility_text: 'LoueCars se esfuerza por garantizar la exactitud y la actualización de la información publicada en este sitio, pero no será responsable de errores, omisiones o daños resultantes del uso de esta información. Los precios mostrados son indicativos y pueden cambiar sin previo aviso.',
    legal_data_title: 'Datos personales',
    legal_data_text: 'Los datos recopilados a través de nuestro formulario de contacto se tratan de conformidad con nuestra política de privacidad, disponible en este sitio. Para ejercer sus derechos (acceso, rectificación, eliminación), contáctenos.',
    legal_cookies_title: 'Cookies',
    legal_cookies_text: 'Este sitio utiliza cookies técnicas y de medición de audiencia. Consulte nuestra política de privacidad para más detalles.',
    legal_law_title: 'Legislación aplicable',
    legal_law_text: 'Este sitio se rige por el derecho beninés. En caso de litigio y a falta de resolución amistosa, los tribunales de Cotonú (Benín) serán los únicos competentes.',
    legal_contact_title: 'Contacto',
    legal_contact_text: 'Para cualquier pregunta sobre el aviso legal, contáctenos en eddiecelle@gmail.com o al +229 97 23 84 83.',
    legal_updated: 'Última actualización: agosto de 2026',
  },

  DE: {
    nav_home: 'Startseite',
    nav_vehicles: 'Unsere Fahrzeuge',
    nav_workshop: 'Werkstatt & SAV',
    nav_contact: 'Kontakt',
    nav_book: 'Buchen',
    lang_label: 'Sprache',

    hero_line1_top: 'Das Auto, das Sie brauchen,',
    hero_line1_bottom: 'wo Sie es brauchen.',
    hero_line2_top: 'Die Flexibilität, die Sie brauchen,',
    hero_line2_bottom: 'zum Preis, den Sie wollen.',
    hero_line3_top: 'Mit oder ohne Fahrer,',
    hero_line3_bottom: 'in Cotonou und ganz Benin.',
    hero_scroll: 'Nach unten scrollen',

    hero_badge: 'Ab 20.000 FCFA / Tag',
    hero_welcome: 'Willkommen bei',
    hero_subtitle: 'Das ideale Auto zum günstigen Preis. Mit oder ohne Fahrer, in Cotonou und ganz Benin — Flughafen, Hotels und alle Ziele.',
    hero_cta_whatsapp: 'Per WhatsApp buchen',
    hero_cta_fleet: 'Unsere Fahrzeuge ansehen',

    stat_vehicles: 'Verfügbare Fahrzeuge',
    stat_availability: 'Verfügbarkeit',
    stat_countries: 'Bediente Länder',
    stat_price: 'FCFA / Tag',

    services_badge: 'Warum uns wählen',
    services_title: 'Unsere',
    services_title2: 'Leistungen',
    services_subtitle: 'Ein lokales Mietwagenunternehmen für Ihre täglichen Fahrten und Reisen.',
    service1_title: 'Mit oder ohne Fahrer',
    service1_desc: 'Tages- oder Langzeitpakete mit erfahrenen Fahrern und maßgeschneidertem Service.',
    service2_title: 'Flughafentransfer',
    service2_desc: 'Ihr Fahrzeug wartet direkt am Ausgang des Flughafens Cotonou auf Sie.',
    service3_title: 'Privatreisen',
    service3_desc: 'Organisierte Fahrten nach Nordbenin, Togo und Ghana mit passendem Fahrzeug.',
    service4_title: '7/7 verfügbar',
    service4_desc: 'Täglich erreichbar für alle Buchungs- und Informationsanfragen.',

    fleet_badge: 'Unsere Flotte',
    fleet_title: 'Unsere',
    fleet_title2: 'Fahrzeuge',
    fleet_subtitle: 'Limousinen, SUVs, Pick-ups und Minibussen — gewartet und zur Miete verfügbar.',
    fleet_cta: 'Gesamte Flotte ansehen',

    cta_title: 'Bereit für das Erlebnis',
    cta_subtitle: 'Mit Sitz in Houéyiho, Cotonou — 7 Tage die Woche verfügbar. Buchen Sie direkt per WhatsApp oder kontaktieren Sie uns für ein Angebot.',
    cta_whatsapp: 'Per WhatsApp buchen',
    cta_contact: 'Kontaktieren Sie uns',

    // contact_badge: 'Kontaktieren Sie uns',
    contact_title: 'Kontaktieren',
    contact_title2: 'Sie uns',
    contact_subtitle: 'Eine Frage? Eine Buchung? Unser Team steht Ihnen 7/7 zur Verfügung.',
    contact_form_title: 'Senden Sie uns eine Nachricht',
    contact_form_subtitle: 'Füllen Sie das Formular aus und wir antworten so schnell wie möglich. Sie können uns auch direkt per WhatsApp erreichen.',
    contact_name: 'Vollständiger Name',
    contact_email: 'E-Mail',
    contact_phone: 'Telefon',
    contact_type: 'Mietart',
    contact_subject: 'Betreff',
    contact_message: 'Nachricht',
    contact_send: 'Nachricht senden',
    contact_sent_title: 'Nachricht gesendet!',
    contact_sent_subtitle: 'Vielen Dank für Ihre Kontaktaufnahme. Wir antworten sehr bald.',
    contact_map_link: 'Houéyiho, Cotonou — In Google Maps öffnen →',

    footer_desc: 'Mietwagenunternehmen in Cotonou, 7/7 verfügbar. Mit oder ohne Fahrer für alle Ihre Fahrten in Benin und darüber hinaus.',
    footer_nav: 'Navigation',
    footer_services: 'Unsere Leistungen',
    footer_contact: 'Kontakt',
    footer_rights: 'Alle Rechte vorbehalten.',
    footer_privacy: 'Datenschutzerklärung',
    footer_legal: 'Impressum',
    footer_svc1: 'Mit Fahrer',
    footer_svc2: 'Ohne Fahrer',
    footer_svc3: 'Flughafentransfer',
    footer_svc4: 'Touristenrundfahrt',
    footer_svc5: 'Reise Nordbenin',
    footer_svc6: 'Transfer Togo / Ghana',

    contact_placeholder_name: 'Ihr Name',
    contact_placeholder_email: 'ihre@email.com',
    contact_placeholder_phone: '+229 00 00 00 00',
    contact_placeholder_type: 'Mietart auswählen',
    contact_placeholder_subject: 'Betreff Ihrer Nachricht',
    contact_placeholder_message: 'Beschreiben Sie Ihre Anfrage (Daten, Ziel, Anzahl Passagiere...)',
    contact_info_address_title: 'Adresse',
    contact_info_phone_title: 'WhatsApp / Telefon',
    contact_info_email_title: 'E-Mail',
    contact_info_availability_title: 'Verfügbarkeit',
    contact_info_availability1: '7 Tage die Woche',
    contact_info_availability2: '24/7 per WhatsApp',
    contact_type1: 'Mit Fahrer',
    contact_type2: 'Ohne Fahrer',
    contact_type3: 'Touristenrundfahrt',
    contact_type4: 'Privatreise (Nordbenin / Togo / Ghana)',
    contact_type5: 'Flughafentransfer',
    contact_type6: 'Langzeitmiete',

    faq_title: 'Häufig gestellte',
    faq_title_highlight: 'Fragen',
    faq_q1: 'Was ist der Mindestmietpreis?',
    faq_a1: 'Unsere Preise starten ab 20.000 FCFA pro Tag. Der Endpreis hängt vom Fahrzeugtyp, der Mietdauer und den gewählten Optionen ab. Kontaktieren Sie uns für ein individuelles Angebot.',
    faq_q2: 'Bieten Sie Flughafentransfer an?',
    faq_a2: 'Ja, wir organisieren Transfers vom Flughafen Cotonou. Teilen Sie uns Ihre Flugdaten im Voraus mit und Ihr Fahrzeug wartet am Ausgang.',
    faq_q3: 'Kann man ein Fahrzeug für Reisen außerhalb Benins mieten?',
    faq_a3: 'Absolut. Wir organisieren Privatfahrten nach Nordbenin, Togo und Ghana mit einem erfahrenen Fahrer, der die Strecken kennt.',

    // Véhicules
    veh_badge: 'Unser Bestand',
    veh_title: 'Unsere',
    veh_title_highlight: 'Fahrzeuge',
    veh_subtitle: 'Limousinen, SUVs, Pick-ups und Minibussen — unsere gesamte Flotte zur Miete ab 20.000 FCFA/Tag.',
    veh_search: 'Fahrzeug suchen...',
    veh_all_brands: 'Alle Marken',
    veh_fuel: 'Kraftstoff',
    veh_found_single: 'Fahrzeug gefunden',
    veh_found_plural: 'Fahrzeuge gefunden',
    veh_none: 'Keine Fahrzeuge gefunden',
    veh_book: 'Buchen',

    // Workshop
    ws_badge: 'Unsere Standorte',
    ws_title: 'Unsere',
    ws_title_highlight: 'Werkstätten & SAV',
    ws_title_rest: 'in Westafrika',
    ws_subtitle: 'Wir sind präsent, um Sie so nah wie möglich an Ihren Bedürfnissen zu bedienen.',
    ws_showroom: 'Showroom',
    ws_approved: 'Zugelassene Werkstatt',
    ws_address: 'Adresse',
    ws_phone: 'Telefon',
    ws_hours: 'Öffnungszeiten',
    ws_services_label: 'Verfügbare Leistungen',
    ws_maps: 'Auf Google Maps ansehen',
    ws_cta_title: 'Benötigen Sie eine',
    ws_cta_title_highlight: 'Wartung',
    ws_cta_subtitle: 'Vereinbaren Sie jetzt einen Termin in der nächstgelegenen Werkstatt.',
    ws_cta_btn: 'Termin vereinbaren',

    // Brands
    brands_badge: 'Unser Katalog',
    brands_title: 'Unsere',
    brands_title_highlight: 'Marken',
    brands_subtitle: 'Entdecken Sie unsere exklusive Palette an Premiumfahrzeugmarken. Klicken Sie auf eine Marke, um ihre Fahrzeuge zu entdecken.',
    brands_vehicle_count_single: 'Fahrzeug',
    brands_vehicle_count_plural: 'Fahrzeuge',
    brands_none: 'Keine Fahrzeuge verfügbar.',
    brands_quote: 'Angebot anfordern',
    brands_showroom: 'Showroom besuchen',

    // WhatsApp-Nachrichten vorausgefüllt
    wa_default: "Hallo, ich möchte Informationen zu Ihren Leistungen erhalten.",
    wa_home_hero: "Hallo LoueCars 👋, ich habe Ihre Website besucht und möchte ein Fahrzeug buchen. Können Sie mich beraten?",
    wa_home_cta: "Hallo LoueCars 👋, ich möchte Informationen zur Fahrzeugmiete erhalten. Bitte kontaktieren Sie mich zurück.",
    wa_navbar_book: "Hallo LoueCars 👋, ich möchte ein Fahrzeug buchen. Können Sie mir Ihre Verfügbarkeit nennen?",
    wa_footer_social: "Hallo LoueCars 👋, ich melde mich von Ihrer Website. Ich hätte gerne Informationen.",
    wa_footer_contact: "Hallo LoueCars 👋, ich möchte Informationen zu Ihren Mietdiensten.",
    wa_floating_button: "Hallo 👋, ich habe eine Frage zu Ihren Leistungen. Können Sie mir helfen?",
    wa_vehicle_book: "Hallo LoueCars 🚗, ich möchte folgendes Fahrzeug buchen: {vehicle} zum Preis von {price} FCFA. Wie ist die Verfügbarkeit?",
    wa_brand_quote: "Hallo LoueCars 🚙, ich möchte ein Angebot für ein Fahrzeug der Marke {brand}{type}. Können Sie mir verfügbare Modelle vorschlagen?",
    wa_contact_form: "Hallo LoueCars 👋, ich kontaktiere Sie über das Formular Ihrer Website.\n\n👤 Name: {name}\n📧 E-Mail: {email}\n📞 Telefon: {phone}\n🏷️ Betreff: {subject}\n🚗 Marke: {brand}\n\n📝 Nachricht:\n{message}",

    // Datenschutzerklärung
    privacy_badge: 'Datenschutz',
    privacy_title: 'Datenschutz-',
    privacy_title2: 'erklärung',
    privacy_subtitle: 'Wir legen großen Wert auf den Schutz Ihrer persönlichen Daten. Erfahren Sie, wie wir sie erfassen, nutzen und schützen.',
    privacy_intro_title: 'Einleitung',
    privacy_intro_text: 'Diese Datenschutzerklärung erklärt, wie LoueCars, eine Autovermietung in Cotonou (Benin), Ihre persönlichen Daten erfasst, verwendet und schützt, wenn Sie unsere Website oder unsere Dienste nutzen.',
    privacy_data_title: 'Daten, die wir erfassen',
    privacy_data_1: 'Identifikationsdaten: Name, Vorname, E-Mail-Adresse und Telefonnummer, die Sie über unser Kontaktformular angeben.',
    privacy_data_2: 'Buchungsdaten: Fahrzeugtyp, Daten, Zielort und Anzahl der Passagiere, wenn Sie uns per WhatsApp oder E-Mail kontaktieren.',
    privacy_data_3: 'Browsing-Daten: besuchte Seiten, Besuchsdauer und IP-Adresse, die über Cookies erfasst werden.',
    privacy_data_4: 'Kommunikationsdaten: Inhalt der mit unserem Team ausgetauschten Nachrichten.',
    privacy_data_5: 'Wir erfassen niemals sensible Daten (ethnische Herkunft, politische Meinungen, Gesundheitsdaten usw.).',
    privacy_use_title: 'Verwendung Ihrer Daten',
    privacy_use_1: 'Beantwortung Ihrer Anfragen und Buchungsanfragen.',
    privacy_use_2: 'Erstellung eines personalisierten Angebots und Vorbereitung Ihrer Miete.',
    privacy_use_3: 'Nachverfolgung Ihrer Buchung und Betreuung vor, während und nach Ihrer Miete.',
    privacy_use_4: 'Verbesserung unserer Dienste und der Qualität unserer Website.',
    privacy_base_title: 'Rechtsgrundlage',
    privacy_base_text: 'Ihre Daten werden auf der Grundlage Ihrer Einwilligung (Kontaktformular, Cookies) und der Erfüllung des von Ihnen angefragten Mietvertrags verarbeitet. Sie werden niemals ohne Ihre Zustimmung zu kommerziellen Zwecken verwendet.',
    privacy_retention_title: 'Speicherung der Daten',
    privacy_retention_text: 'Ihre Daten werden nur so lange aufbewahrt, wie es für die oben beschriebenen Zwecke erforderlich ist: höchstens 3 Jahre nach Ihrem letzten Kontakt für Akquisitionsdaten und 10 Jahre für mietbezogene Dokumente, gemäß den in Benin geltenden rechtlichen und steuerlichen Verpflichtungen.',
    privacy_share_title: 'Weitergabe der Daten',
    privacy_share_text: 'Ihre Daten werden weder verkauft, vermietet noch an Dritte weitergegeben. Sie werden nur mit Anbietern geteilt, die für unsere Dienste unbedingt erforderlich sind (Website-Hosting, E-Mail-Anbieter), und nur im erforderlichen Umfang.',
    privacy_cookies_title: 'Cookies',
    privacy_cookies_text: 'Unsere Website verwendet technische Cookies, die für ihren Betrieb unerlässlich sind, sowie anonymisierte Reichweitenmessungs-Cookies. Sie können Ihren Browser so konfigurieren, dass Cookies abgelehnt werden; dies kann jedoch einige Funktionen der Website einschränken.',
    privacy_rights_title: 'Ihre Rechte',
    privacy_rights_1: 'Zugang zu Ihren persönlichen Daten.',
    privacy_rights_2: 'Berichtigung unrichtiger oder unvollständiger Daten beantragen.',
    privacy_rights_3: 'Löschung Ihrer Daten unter den gesetzlich vorgesehenen Bedingungen beantragen.',
    privacy_rights_4: 'Ihre Einwilligung für darauf basierende Verarbeitungen jederzeit widerrufen.',
    privacy_security_title: 'Sicherheit',
    privacy_security_text: 'Wir ergreifen geeignete technische und organisatorische Maßnahmen, um Ihre Daten vor unbefugtem Zugriff, Verlust, Veränderung oder Offenlegung zu schützen.',
    privacy_contact_title: 'Kontakt',
    privacy_contact_text: 'Bei Fragen zu dieser Richtlinie oder zur Ausübung Ihrer Rechte kontaktieren Sie uns per E-Mail an eddiecelle@gmail.com, telefonisch unter +229 97 23 84 83 oder über unsere Kontaktseite.',
    privacy_updated: 'Zuletzt aktualisiert: August 2026',

    // Impressum
    legal_badge: 'Rechtliche Hinweise',
    legal_title: 'Rechtliche',
    legal_title2: 'Hinweise',
    legal_subtitle: 'Rechtliche Hinweise zur Website der Agentur LoueCars, einem Fahrzeugvermietungsunternehmen in Benin.',
    legal_publisher_title: 'Herausgeber der Website',
    legal_publisher_text: 'LoueCars — Autovermietung. Adresse: Houéyiho, Cotonou, Benin. E-Mail: eddiecelle@gmail.com. Telefon: +229 97 23 84 83.',
    legal_director_title: 'Verantwortlicher für die Veröffentlichung',
    legal_director_text: 'Der Verantwortliche für die Veröffentlichung ist der gesetzliche Vertreter der Agentur LoueCars. Er ist für alle auf dieser Website veröffentlichten Inhalte verantwortlich.',
    legal_host_title: 'Hosting',
    legal_host_text: 'Die Website wird von einem technischen Anbieter gehostet, der die Verfügbarkeit und Sicherheit der Plattform gewährleistet. Die vollständigen Kontaktdaten des Hosters sind auf Anfrage erhältlich.',
    legal_ip_title: 'Geistiges Eigentum',
    legal_ip_text: 'Alle Inhalte dieser Website (Texte, Logos, Bilder, Marken, Struktur, Fotografien) sind durch das Recht des geistigen Eigentums geschützt. Jede Vervielfältigung, Verbreitung oder Nutzung, ganz oder teilweise, ohne vorherige schriftliche Genehmigung von LoueCars ist strengstens untersagt.',
    legal_responsibility_title: 'Haftung',
    legal_responsibility_text: 'LoueCars bemüht sich, die Richtigkeit und Aktualisierung der auf dieser Website veröffentlichten Informationen zu gewährleisten, haftet jedoch nicht für Fehler, Auslassungen oder Schäden, die aus der Nutzung dieser Informationen entstehen. Die angezeigten Preise sind unverbindlich und können sich ohne Vorankündigung ändern.',
    legal_data_title: 'Personenbezogene Daten',
    legal_data_text: 'Die über unser Kontaktformular erfassten Daten werden gemäß unserer Datenschutzerklärung verarbeitet, die auf dieser Website verfügbar ist. Zur Ausübung Ihrer Rechte (Auskunft, Berichtigung, Löschung) kontaktieren Sie uns.',
    legal_cookies_title: 'Cookies',
    legal_cookies_text: 'Diese Website verwendet technische und Reichweitenmessungs-Cookies. Weitere Details finden Sie in unserer Datenschutzerklärung.',
    legal_law_title: 'Anwendbares Recht',
    legal_law_text: 'Diese Website unterliegt dem beninischen Recht. Im Streitfall und mangels gütlicher Einigung sind ausschließlich die Gerichte von Cotonou (Benin) zuständig.',
    legal_contact_title: 'Kontakt',
    legal_contact_text: 'Bei Fragen zum Impressum kontaktieren Sie uns unter eddiecelle@gmail.com oder +229 97 23 84 83.',
    legal_updated: 'Zuletzt aktualisiert: August 2026',
  },

  ZH: {
    nav_home: '首页',
    nav_vehicles: '我们的车辆',
    nav_workshop: '维修站',
    nav_contact: '联系我们',
    nav_book: '立即预订',
    lang_label: '语言',

    hero_line1_top: '您需要的用车，',
    hero_line1_bottom: '随时随地为您服务。',
    hero_line2_top: '您需要的灵活性，',
    hero_line2_bottom: '以您满意的价格。',
    hero_line3_top: '有无司机均可，',
    hero_line3_bottom: '服务科托努及贝宁全境。',
    hero_scroll: '向下滚动',

    hero_badge: '每天起价20,000 FCFA',
    hero_welcome: '欢迎来到',
    hero_subtitle: '价格实惠的理想用车。有无司机均可，服务科托努及贝宁全境——机场、酒店及所有目的地。',
    hero_cta_whatsapp: 'WhatsApp预订',
    hero_cta_fleet: '查看车辆',

    stat_vehicles: '可用车辆',
    stat_availability: '全年无休',
    stat_countries: '服务国家',
    stat_price: 'FCFA / 天',

    services_badge: '为什么选择我们',
    services_title: '我们的',
    services_title2: '服务',
    services_subtitle: '本地汽车租赁机构，专为您的日常出行和旅途而设。',
    service1_title: '有无司机均可',
    service1_desc: '按日或长期租赁套餐，配备经验丰富的司机，提供量身定制的服务。',
    service2_title: '机场接送',
    service2_desc: '您的车辆将在科托努机场出口等候，让您的行程无缝开始。',
    service3_title: '私人旅行',
    service3_desc: '前往贝宁北部、多哥和加纳的有组织行程，配备适合您路线的车辆。',
    service4_title: '每周7天可用',
    service4_desc: '每天均可联系，处理任何预订或咨询请求。',

    fleet_badge: '我们的车队',
    fleet_title: '我们的',
    fleet_title2: '车辆',
    fleet_subtitle: '轿车、SUV、皮卡和小巴——维护良好，可供租用。',
    fleet_cta: '查看全部车队',

    cta_title: '准备好体验',
    cta_subtitle: '位于科托努Houéyiho——每周7天可用。直接通过WhatsApp预订或联系我们获取报价。',
    cta_whatsapp: 'WhatsApp预订',
    cta_contact: '联系我们',

    // contact_badge: '联系我们',
    contact_title: '联系我们',
    contact_title2: '联系',
    contact_subtitle: '有问题或需要预订？我们的团队每周7天为您提供服务。',
    contact_form_title: '发送消息',
    contact_form_subtitle: '填写下面的表格，我们将尽快回复您。您也可以直接通过WhatsApp联系我们。',
    contact_name: '姓名',
    contact_email: '电子邮件',
    contact_phone: '电话',
    contact_type: '租赁类型',
    contact_subject: '主题',
    contact_message: '消息',
    contact_send: '发送消息',
    contact_sent_title: '消息已发送！',
    contact_sent_subtitle: '感谢您联系我们，我们将很快回复。',
    contact_map_link: 'Houéyiho, 科托努 — 在Google地图中打开 →',

    footer_desc: '科托努汽车租赁机构，每周7天可用。有无司机均可，服务贝宁及周边地区。',
    footer_nav: '导航',
    footer_services: '我们的服务',
    footer_contact: '联系方式',
    footer_rights: '版权所有。',
    footer_privacy: '隐私政策',
    footer_legal: '法律声明',
    footer_svc1: '含司机',
    footer_svc2: '不含司机',
    footer_svc3: '机场接送',
    footer_svc4: '旅游线路',
    footer_svc5: '贝宁北部行程',
    footer_svc6: '多哥/加纳转运',

    contact_placeholder_name: '您的姓名',
    contact_placeholder_email: 'your@email.com',
    contact_placeholder_phone: '+229 00 00 00 00',
    contact_placeholder_type: '选择租赁类型',
    contact_placeholder_subject: '消息主题',
    contact_placeholder_message: '描述您的需求（日期、目的地、乘客人数...）',
    contact_info_address_title: '地址',
    contact_info_phone_title: 'WhatsApp / 电话',
    contact_info_email_title: '电子邮件',
    contact_info_availability_title: '可用时间',
    contact_info_availability1: '每周7天',
    contact_info_availability2: 'WhatsApp 24小时',
    contact_type1: '含司机',
    contact_type2: '不含司机',
    contact_type3: '旅游线路',
    contact_type4: '私人行程（贝宁北部/多哥/加纳）',
    contact_type5: '机场接送',
    contact_type6: '长期租赁',

    faq_title: '常见',
    faq_title_highlight: '问题',
    faq_q1: '最低租赁费用是多少？',
    faq_a1: '我们的价格从每天20,000 FCFA起。最终价格取决于车型、租赁时长和所选选项。请联系我们获取个性化报价。',
    faq_q2: '你们提供机场接送服务吗？',
    faq_a2: '是的，我们提供科托努机场接送服务。只需提前告知您的航班信息，我们的车辆将在出口等候您。',
    faq_q3: '可以租车出境吗？',
    faq_a3: '当然可以。我们可以安排前往贝宁北部（彭贾里、W公园）、多哥和加纳的私人行程，配备熟悉路线的经验丰富司机。',

    // Véhicules
    veh_badge: '我们的库存',
    veh_title: '我们的',
    veh_title_highlight: '车辆',
    veh_subtitle: '轿车、SUV、皮卡和小巴——我们全部车队可供租用，起价20,000 FCFA/天。',
    veh_search: '搜索车辆...',
    veh_all_brands: '所有品牌',
    veh_fuel: '燃料',
    veh_found_single: '辆车辆已找到',
    veh_found_plural: '辆车辆已找到',
    veh_none: '未找到车辆',
    veh_book: '预订',

    // Workshop
    ws_badge: '我们的门店',
    ws_title: '我们在',
    ws_title_highlight: '西非的维修站',
    ws_title_rest: '',
    ws_subtitle: '我们随时为您提供最贴近需求的服务。',
    ws_showroom: '展厅',
    ws_approved: '授权维修站',
    ws_address: '地址',
    ws_phone: '电话',
    ws_hours: '营业时间',
    ws_services_label: '可用服务',
    ws_maps: '在Google地图上查看',
    ws_cta_title: '需要',
    ws_cta_title_highlight: '维修保养',
    ws_cta_subtitle: '立即在距您最近的维修站预约。',
    ws_cta_btn: '预约',

    // Brands
    brands_badge: '我们的目录',
    brands_title: '我们的',
    brands_title_highlight: '品牌',
    brands_subtitle: '探索我们独家的知名汽车品牌系列。点击某个品牌即可查看其车辆。',
    brands_vehicle_count_single: '辆车辆',
    brands_vehicle_count_plural: '辆车辆',
    brands_none: '暂无可用车辆。',
    brands_quote: '申请报价',
    brands_showroom: '参观展厅',

    // 预填WhatsApp消息
    wa_default: "您好，我想了解一下你们的服务信息。",
    wa_home_hero: "您好 LoueCars 👋，我访问了您的网站，想要预订一辆车。您能给我一些建议吗？",
    wa_home_cta: "您好 LoueCars 👋，我想了解一下租车信息。请联系我。",
    wa_navbar_book: "您好 LoueCars 👋，我想预订一辆车。请问有哪些可用的车型？",
    wa_footer_social: "您好 LoueCars 👋，我从您的网站上找到您的联系方式。想了解一下信息。",
    wa_footer_contact: "您好 LoueCars 👋，我想了解一下你们的租赁服务信息。",
    wa_floating_button: "您好 👋，我有一个关于您服务的问题。能帮我吗？",
    wa_vehicle_book: "您好 LoueCars 🚗，我想预订以下车辆：{vehicle}，价格：{price} FCFA。请问有哪些日期可用？",
    wa_brand_quote: "您好 LoueCars 🚙，我想要{brand}品牌{type}的车辆报价。能推荐一些可用的车型吗？",
    wa_contact_form: "您好 LoueCars 👋，我是通过您网站上的表单联系您的。\n\n👤 姓名：{name}\n📧 邮箱：{email}\n📞 电话：{phone}\n🏷️ 主题：{subject}\n🚗 品牌：{brand}\n\n📝 留言：\n{message}",

    // 隐私政策
    privacy_badge: '隐私保护',
    privacy_title: '隐私',
    privacy_title2: '政策',
    privacy_subtitle: '我们非常重视对您个人信息的保护。了解我们如何收集、使用和保护您的信息。',
    privacy_intro_title: '简介',
    privacy_intro_text: '本隐私政策说明 LoueCars（贝宁科托努的汽车租赁公司）在您使用我们的网站或服务时如何收集、使用和保护您的个人数据。',
    privacy_data_title: '我们收集的数据',
    privacy_data_1: '身份信息：您通过我们的联系表单提供的姓名、电子邮箱和电话号码。',
    privacy_data_2: '预订信息：当您通过 WhatsApp 或电子邮件联系我们时提供的车辆类型、日期、目的地和乘客人数。',
    privacy_data_3: '浏览信息：通过 Cookie 收集的访问页面、浏览时长和 IP 地址。',
    privacy_data_4: '沟通信息：与我们团队往来的消息内容。',
    privacy_data_5: '我们从不收集敏感数据（种族、政治观点、健康数据等）。',
    privacy_use_title: '数据的使用',
    privacy_use_1: '回复您的咨询和预订请求。',
    privacy_use_2: '为您提供个性化报价并准备租赁事宜。',
    privacy_use_3: '跟进您的预订，并在租赁前、租赁中和租赁后为您提供支持。',
    privacy_use_4: '改进我们的服务和我们网站的质量。',
    privacy_base_title: '法律依据',
    privacy_base_text: '我们基于您的同意（联系表单、Cookie）以及您所请求的租赁合同的履行来处理您的数据。未经您的同意，我们绝不会将您的数据用于商业目的。',
    privacy_retention_title: '数据保存',
    privacy_retention_text: '您的数据仅在我们实现上述目的所需的时间内保存：您的最后一次联系后最多保留 3 年（用于客户开发数据），租赁相关文件保留 10 年，并遵循贝宁现行法律法规和税务义务。',
    privacy_share_title: '数据共享',
    privacy_share_text: '您的数据不会被出售、出租或转让给第三方。我们仅在我们服务所必需的范围内与相关服务商（网站托管商、邮件服务商）共享。',
    privacy_cookies_title: 'Cookies',
    privacy_cookies_text: '我们的网站使用运行所必需的技术性 Cookie 以及匿名的访问统计 Cookie。您可以设置浏览器拒绝 Cookie，但这可能会限制网站的某些功能。',
    privacy_rights_title: '您的权利',
    privacy_rights_1: '访问您的个人数据。',
    privacy_rights_2: '要求更正不准确或不完整的数据。',
    privacy_rights_3: '在法律规定的条件下要求删除您的数据。',
    privacy_rights_4: '随时撤回您对基于同意的数据处理所给予的授权。',
    privacy_security_title: '安全',
    privacy_security_text: '我们采取适当的技术和组织措施，保护您的数据免受未经授权的访问、丢失、篡改或泄露。',
    privacy_contact_title: '联系我们',
    privacy_contact_text: '如需咨询本政策或行使您的权利，请通过电子邮件 eddiecelle@gmail.com、电话 +229 97 23 84 83 或我们的联系页面与我们联系。',
    privacy_updated: '最后更新：2026年8月',

    // 法律声明
    legal_badge: '法律信息',
    legal_title: '法律',
    legal_title2: '声明',
    legal_subtitle: '与 LoueCars 汽车租赁公司网站相关的法律信息。',
    legal_publisher_title: '网站编辑',
    legal_publisher_text: 'LoueCars — 汽车租赁公司。地址：贝宁科托努 Houéyiho。电子邮箱：eddiecelle@gmail.com。电话：+229 97 23 84 83。',
    legal_director_title: '出版负责人',
    legal_director_text: '出版负责人是 LoueCars 公司的法定代表人，对本网站发布的所有内容负责。',
    legal_host_title: '网站托管',
    legal_host_text: '本网站由技术服务商托管，以保证平台的可用性和安全性。可应要求提供托管商的完整联系方式。',
    legal_ip_title: '知识产权',
    legal_ip_text: '本网站的所有内容（文字、标志、图片、商标、结构、照片）均受知识产权法律保护。未经 LoueCars 事先书面许可，禁止以任何方式全部或部分复制、传播或使用。',
    legal_responsibility_title: '责任声明',
    legal_responsibility_text: 'LoueCars 力求确保本网站所发布信息的准确性和及时更新，但对于因使用这些信息而产生的错误、遗漏或损失不承担任何责任。所示价格仅供参考，如有变动恕不另行通知。',
    legal_data_title: '个人数据',
    legal_data_text: '通过我们的联系表单收集的数据将按照本网站提供的隐私政策进行处理。如需行使您的权利（访问、更正、删除），请联系我们。',
    legal_cookies_title: 'Cookies',
    legal_cookies_text: '本网站使用技术性 Cookie 和访问统计 Cookie。详情请参阅我们的隐私政策。',
    legal_law_title: '适用法律',
    legal_law_text: '本网站受贝宁法律管辖。发生争议且未能友好解决时，贝宁科托努法院拥有专属管辖权。',
    legal_contact_title: '联系',
    legal_contact_text: '如对本法律声明有任何疑问，请通过 eddiecelle@gmail.com 或 +229 97 23 84 83 联系我们。',
    legal_updated: '最后更新：2026年8月',
  },
} as const;

export type TranslationKey = keyof typeof translations.FR;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>('FR');

  const t = (key: TranslationKey): string => {
    return (translations[lang] as Record<string, string>)[key] ?? (translations.FR as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
};
